# Generated by Django 3.2.7 on 2021-10-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='申请人')),
                ('cities', models.CharField(max_length=16, verbose_name='所属项目')),
                ('_type', models.CharField(max_length=16, verbose_name='需求类型')),
                ('description', models.CharField(max_length=256, verbose_name='需求描述')),
                ('status', models.CharField(default='进行中', max_length=8, verbose_name='状态')),
                ('processor', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='处理人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'permissions': (('can_view_all', 'Can view all'),),
            },
        ),
    ]
