# Generated by Django 3.2.7 on 2021-11-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='telephone',
            field=models.CharField(default=0, max_length=15, verbose_name='电话'),
            preserve_default=False,
        ),
    ]
