# Generated by Django 3.2.7 on 2021-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_table_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
