# Generated by Django 3.2.7 on 2021-12-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_table_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='需求描述'),
        ),
    ]
