# Generated by Django 3.2.7 on 2021-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='sn_BIOS',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='BIOS序列号'),
        ),
        migrations.AlterField(
            model_name='table',
            name='sn_mainboard',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主板序列号'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('使用中', '使用中'), ('库存', '库存'), ('出库', '出库'), ('报废', '报废'), ('损坏', '损坏'), ('出库审批', '出库审批'), ('报废审批', '报废审批')], default='库存', max_length=16, verbose_name='状态'),
        ),
    ]
