# Generated by Django 3.2.7 on 2021-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20210918_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='cpu',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='cpu'),
        ),
    ]
