# Generated by Django 3.2.4 on 2021-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_table_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': (('can_view', 'Can view the page'),), 'verbose_name_plural': '资产表'},
        ),
    ]
