# Generated by Django 3.2.4 on 2021-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_table_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='deployment_plan',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='部署规划'),
        ),
    ]
