# Generated by Django 3.2.4 on 2021-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_table_deployment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='os',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统'),
        ),
    ]
