# Generated by Django 3.2.4 on 2021-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_table_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='table',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='位置'),
        ),
    ]
